### ISSUE TITLE
Some failing conversions

### ISSUE THREAD

**Issue by sven-oly** [googlei18n/myanmar-tools#21]
Unicode -> Zawgyi conversion failures:

Input: U+1000 103b 103d should give 
Expected: Z-1000 103c **107d**
Observed: Z-1000 103a **103c** 

Zawgyi -> Unicode conversion failures:
Input: Z-108f 103c 1036 1031 1010 1038 103a
Expected: U+1014 103d 1036 1010  **103b 1031** 1038  
Observed: U+1014 103d 1036 1010 **1031 103**b 1038

**Comment by sffc** [comment]
Fixed by #23
