### ISSUE TITLE
Illegal ID Zawgyi-my

### ISSUE THREAD

**Issue by HsuWai** [googlei18n/myanmar-tools#4]
When I run your demo java application, Exception is java.lang.IllegalArgumentException: Illegal ID Zawgyi-my. Which library version of ICU is used?

**Comment by sffc** [comment]
Hi,
You need at least CLDR 30 / ICU 58 for the `Zawgyi-my` transform.

**Comment by HsuWai** [comment]
Thanks a lot. It's ok with ICU 58.
