### ISSUE TITLE
Publish Ruby client to rubygems

### ISSUE THREAD

**Issue by sffc** [googlei18n/myanmar-tools#5]
#3 added a Ruby client to myanmar-tools.  It would be great to see it published to rubygems for easy installation.

It is okay for either @kirankarki or someone from Google to publish the gem, as long as a Google-owned account has access to push updates.

**Comment by kirankarki** [comment]
Hi @sffc,

Thank you for this fix [1de7e70](https://github.com/googlei18n/myanmar-tools/commit/1de7e701d7e4a6b807dba54c1e76d67f66b8adae) and merging the pull request.

I will publish the gem to [rubygems](https://rubygems.org), and also add usage sample for this client.

**Comment by kirankarki** [comment]
Hi @sffc,

I have published the [gem](https://rubygems.org/gems/myanmar-tools) to rubygems host.
And also modified the usage guide and added demo of this client under `samples/ruby`.

I have created a [pull request ](https://github.com/googlei18n/myanmar-tools/pull/6) for the above changes.

**Comment by sffc** [comment]
Thank you!

Can you please give the following two accounts access to edit the gem on rubygems.org?

- "google-myanmar-tools-user"  --> this is a Google-owned account so that we are able to push updates in the future
- "sffc"  --> this is my account

I made a few changes to the documentation.  The ICU converter is available in Ruby, so I put that in the example code and updated the README accordingly.

https://github.com/googlei18n/myanmar-tools/compare/49fb350...master

I'm also a fan of `bundle add` as an alternative to `gem install`. 🙂

**Comment by kirankarki** [comment]
Hi @sffc,

Thank you for the amendments.

I have added the above two accounts to gem owners list.

https://rubygems.org/gems/myanmar-tools

**Comment by sffc** [comment]
Looks good, and thanks again for the contribution!
